// <auto-generated />
namespace WorldBuilder.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class fixedminorinconvinience : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixedminorinconvinience));
        
        string IMigrationMetadata.Id
        {
            get { return "202004090552415_fixed minor inconvinience"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
